require(tidyverse)
require(stringr)

#param data is a tibble
#param char_col is a name of a character column within data
#param len_longest_str is the maximum number of words in any string within char_col

word_count <- function(data, char_col, len_longest_str = 30) {
  ##  Provides word count from character column of a tibble.
  if(!is.tibble(data)) {stop("data is not a tibble, errors may occur")}
  
  char_col <- enquo(char_col)
  char_col_i <- quo_name(char_col)
  
  data %>% 
    select(!!char_col) %>% 
    select_if(function(x) is.factor(x) || is.character(x)) %>% # Gives error when column type isn't chr of fct
    mutate(!!char_col_i := str_remove_all(!!char_col, '[[:punct:]]')) %>% # Removes punctuation
    mutate(!!char_col_i := str_split(!!char_col, ' ')) %>% #Separate words into a vec of strings
    separate(char_col_i, into = paste0('col', 1:len_longest_str), fill = 'right') %>% # Puts each element of vector into into a column
    select(-col1) %>%                   # First column will consist of all 'c', this removes it
    gather(value = word) %>%               # Combines all columns into one
    select(-key) %>%                       # Removes 'key' column generated by gather
    janitor::remove_empty(c('rows')) %>%   # Remove all NA values
    filter(word != "") %>%                 # Remove all empty strings
    mutate(word = str_to_lower(word)) %>%  # Puts everything in lowercarse
    group_by(word) %>%                     # Groups by word
    summarize(freq = n()) %>%              # Calculates the number of each word
    arrange(desc(freq))                    # Sorts the tibble by descending frequency
}

# Catches the error thrown by select_if and gives an error message
word_count <- possibly(.f = word_count, 
                       otherwise = 'char_col should be a character column (or factor)', 
                       quiet = FALSE)
